# 1. Create a Discord bot on the Discord Developer Portal: https://discord.com/developers/applications
# 2. Get the token from the "Bot" tab
# 3. Insert the token below
# 4. Run the "/dvreload" command or reload the server
# 5. Give your players access to send a command to the bot (e.g., invite it to your Discord server)
token: "DISCORD_BOT_TOKEN"

# Language configuration. Available files in the lang folder: en, ua
language: en

# Global limit for how many accounts can play from one IP address
# Note: You can override this for specific users using /dvdecision allow <discordId | playerName> <amount>
default-max-accounts-per-ip: 1

# The ID of your Discord server (guild). If a player isn't on the server, they won't be allowed in.
# Leave this field blank ("") to disable this check.
required-guild-id: ""

# A link to the Discord server invitation that will be displayed to the player if they are not on the server.
discord-invite-link: "https://discord.gg/yourinvite"

# If configured, multi-account alerts will be sent directly to your Discord staff channel
discord-alerts:
  channel-id: "" # E.g., "123456789012345678"
  admin-role-id: "" # The role ID required to click "Allow" / "Block" buttons